# Generated by Django 4.2.29 on 2026-04-07 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['user'], name='address_user_id_598b7f_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['pincode'], name='address_pincode_bc1382_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['city'], name='address_city_db657e_idx'),
        ),
    ]
