# Generated by Django 4.2.29 on 2026-04-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='orderstatus',
            index=models.Index(fields=['name'], name='order_statu_name_91c4fc_idx'),
        ),
    ]
