# Generated by Django 4.2.29 on 2026-04-08 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_add_payment_method'),
        ('orders', '0002_add_orderstatus_name_index'),
    ]

    operations = [
    ]
