# Generated by Django 4.2.29 on 2026-05-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulepermission',
            name='can_add_banner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modulepermission',
            name='can_delete_banner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modulepermission',
            name='can_edit_banner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modulepermission',
            name='can_view_banner',
            field=models.BooleanField(default=False),
        ),
    ]
