# Generated by Django 4.2.29 on 2026-05-19 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='banner',
            new_name='banner_is_acti_538185_idx',
            old_name='banner_is_ac_banner__idx',
        ),
        migrations.RenameIndex(
            model_name='banner',
            new_name='banner_positio_d61acc_idx',
            old_name='banner_positio_idx',
        ),
        migrations.RenameIndex(
            model_name='banner',
            new_name='banner_start_d_7baf7b_idx',
            old_name='banner_start_d_idx',
        ),
    ]
