# Generated by Django 4.2.29 on 2026-06-21 12:39

import banners.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_rename_banner_is_ac_banner__idx_banner_is_acti_538185_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='end_date',
            field=models.DateTimeField(blank=True, default=banners.models.Banner.get_default_end_date, null=True),
        ),
    ]
